apiVersion: v2
name: onelens-agent-base
description: Base Helm chart for the OneLens Agent
type: application
version: 2.1.104
appVersion: 2.1.104
maintainers:
  - name: OneLens
    email: support@onelens.cloud
