apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onelens-agent.fullname" . }}-secrets
type: Opaque
data:
  API_BASE_URL: {{ .Values.secrets.API_BASE_URL | b64enc }}
  CLUSTER_TOKEN: {{ .Values.secrets.CLUSTER_TOKEN | b64enc }}
  REGISTRATION_ID: {{ .Values.secrets.REGISTRATION_ID | b64enc }} 