{{- if eq .Values.metricsBackend "victoriametrics" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: onelens-agent-prometheus-server
  labels:
    {{- include "onelens-agent.labels" . | nindent 4 }}
    component: victoriametrics
data:
  prometheus.yml: |
    global:
      scrape_interval: 1m
      scrape_timeout: 10s
      evaluation_interval: 1m
    scrape_configs:
      {{- .Values.victoriaMetrics.scrapeConfigs | nindent 6 }}
    {{- if .Values.victoriaMetrics.extraScrapeConfigs }}
      {{- .Values.victoriaMetrics.extraScrapeConfigs | nindent 6 }}
    {{- end }}
{{- end }}
