{{- if eq .Values.metricsBackend "victoriametrics" }}
apiVersion: v1
kind: Service
metadata:
  name: onelens-agent-prometheus-server
  labels:
    {{- include "onelens-agent.labels" . | nindent 4 }}
    component: victoriametrics
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8428
      protocol: TCP
      name: http
  selector:
    app: onelens-agent-prometheus-server
    component: victoriametrics
{{- end }}
