apiVersion: batch/v1
kind: Job
metadata:
  name: helm-deployer-job
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: helm-deployer
    spec:
      restartPolicy: Never
      serviceAccountName: helm-deployer-sa
      containers:
        - name: helmdeployer
          image: onelens/helmdeployer:latest
          env:
            - name: TENANT_NAME
              value: "your-tenant-name"  # Replace with actual tenant name
            - name: ONELENS_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: onelens-secret
                  key: secret-token  # Replace with actual secret key
apiVersion: batch/v1
kind: CronJob
metadata:
  name: helm-deployer-cronjob
  namespace: default
spec:
  schedule: "0 2 * * *"  
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: helm-deployer
        spec:
          restartPolicy: Never
          serviceAccountName: helm-deployer-sa
          containers:
            - name: helmdeployer
              image: onelens/helmdeployer:latest
              env:
                - name: TENANT_NAME
                  value: "your-tenant-name"  
                - name: ONELENS_SECRET_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: onelens-secret
                      key: secret-token 
