{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  suspend: {{ .Values.cronjob.suspend }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 120
      template:
        spec:
          serviceAccountName: {{ .Values.cronjob.serviceAccount.name }}
          {{- with .Values.cronjob.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cronjob.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Values.cronjob.name }}
              image: {{ .Values.cronjob.image }}:{{ .Values.cronjob.imageTag }}
              imagePullPolicy: {{ .Values.cronjob.imagePullPolicy }}
              env:
                {{- range $key, $value := .Values.cronjob.env }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
                - name: REGISTRATION_ID
                  valueFrom:
                    secretKeyRef:
                      name: onelens-agent-secrets
                      key: REGISTRATION_ID
                - name: CLUSTER_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: onelens-agent-secrets
                      key: CLUSTER_TOKEN
                
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
{{- end }}
