{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    spec:
      serviceAccountName: {{ .Values.job.serviceAccount.name }}
      containers:
        - name: {{ .Values.job.name }}
          image: {{ .Values.job.image }}:{{ .Values.job.imageTag }}
          imagePullPolicy: {{ .Values.job.imagePullPolicy }}
          env:
            {{- range $key, $value := .Values.job.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
      restartPolicy: {{ .Values.job.restartPolicy }}

      {{- with .Values.job.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.job.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
