apiVersion: v2
name: job-cronjob-chart
description: A Helm chart for deploying Kubernetes Jobs and CronJobs
version: 0.1.0
type: application

maintainers:
  - name: Your Name
    email: your.email@example.com

keywords:
  - job
  - cronjob
  - kubernetes
  - helm

sources:
  - https://github.com/your-repo/job-cronjob-chart

templates:
  - name: _helpers.tpl
    path: templates/_helpers.tpl
