name: PR Jira Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  jira-check:
    uses: ./.github/workflows/pr-jira-check-reusable.yml
    secrets: inherit
