name: Validate New Helm Chart Package

on:
  workflow_run:
    workflows:
      - Build and Deploy OnelensDeployer and Package Onelens-Agent Helm Chart
    types:
      - completed

jobs:
  validate-new-helm-package:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Find latest .tgz file
        id: find-latest
        run: |
          TGZ=$(ls -t *.tgz | head -n 1 || true)
          echo "Latest .tgz file: $TGZ"
          echo "tgz_file=$TGZ" >> $GITHUB_OUTPUT

      - name: Fail if no .tgz file found
        if: steps.find-latest.outputs.tgz_file == ''
        run: |
          echo "❌ No .tgz file found in repository."
          exit 1

      - name: Extract and validate Helm chart
        run: |
          TGZ_FILE="${{ steps.find-latest.outputs.tgz_file }}"
          echo "✅ Validating chart file: $TGZ_FILE"

          mkdir -p extracted
          tar -xzf "$TGZ_FILE" -C extracted

          CHART_DIR=$(basename "$TGZ_FILE" .tgz)
          FULL_PATH="extracted/$CHART_DIR"

          echo "🔍 Linting $FULL_PATH"
          helm lint "$FULL_PATH"

          echo "🔍 Rendering $FULL_PATH"
          helm template test-render "$FULL_PATH"

          echo "🧪 Installing $FULL_PATH with --dry-run"
          helm install test-release "$FULL_PATH" --dry-run --debug
