name: Validate New Helm Chart Package

on:
  workflow_run:
    workflows: ["Build and Deploy OnelensDeployer and Package Onelens-Agent Helm Chart"]
    types:
      - completed
    branches:
      - master

jobs:
  validate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Find newly added .tgz file
        id: find-latest
        run: |
          echo "🔍 Checking for new .tgz files added in last commit..."
          TGZ_FILE=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.workflow_run.head_sha }} | grep '\.tgz$' | head -n 1 || true)
          
          if [ -z "$TGZ_FILE" ]; then
            echo "No .tgz file found in commit!"
            exit 1
          fi

          echo "✅ Found TGZ file: $TGZ_FILE"
          echo "tgz_file=$TGZ_FILE" >> $GITHUB_OUTPUT

      - name: Extract and validate Helm chart
        run: |
          TGZ_FILE="${{ steps.find-latest.outputs.tgz_file }}"
          echo "✅ Validating chart file: $TGZ_FILE"

          mkdir -p extracted
          tar -xzf "$TGZ_FILE" -C extracted

          # Auto-detect the directory inside the .tgz
          CHART_DIR=$(ls extracted | head -n 1)
          FULL_PATH="extracted/$CHART_DIR"

          echo "📁 Found chart at $FULL_PATH"

          echo "🔍 Linting $FULL_PATH"
          helm lint "$FULL_PATH"

          echo "🔍 Rendering $FULL_PATH"
          helm template test-render "$FULL_PATH"

          echo "🧪 Installing $FULL_PATH with --dry-run"
          helm install test-release "$FULL_PATH" --dry-run --debug
